[package]
name = "konnektoren-web-game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "konnektoren-web-game-pwa"
path = "src/bin/main.rs"

[dependencies]
console_log = "1.0.0"
log = "0.4.21"
yew = { version = "0.21.0", features = ["csr"] }
