id: "verben-mit-prapositionen-pkg"
name: "Verben mit Präpositionen"
description: "Learn the verbs with prepositions of the German language"
challenge: "verben-mit-prapositionen-pkg"
variant: "custom-package"
tasks: 10
unlock_points: 0
position: [8, 3]
