= Developer Guide

This guide provides information for developers who want to contribute to the project.

== Quickstart

Clone the repository

[source,bash]
----
git clone git@github.com:Konnektoren/konnektoren-web-game.git
----

then compile and serve the page with

[source,bash]
----
trunk serve
----

then visit http://localhost:8080

== Repository Structure

The repository is structured as follows:

* `docs/` contains the developer guide
* `src/` contains the source code
* `src/assets/challenges/` contains the challenge assets
* `src/assets/i18n/` contains the internationalization assets
* `styles/` contains the scss styles
* `Cargo.toml` contains the package metadata
* `README.adoc` contains the project documentation

== Contributing

To contribute to the project, follow these steps:

1. Fork the repository
2. Create a new branch
3. Make your changes
4. Push your changes to your fork
5. Open a pull request

== Create a New Challenge Dataset

To create a new challenge dataset, follow these steps:

* Create a new file in `src/assets/challenges/` for the challenge data like `src/assets/challenges/articles.yml`

[source,yaml]
----
include::../src/assets/challenges/articles.yml[lines=1..20]
----

* Add the challenge data to the level file like `src/assets/challenges/levels.yml`

[source,yaml]
----
include::../src/assets/challenges/level_a1.yml[lines=1..11]
----

* Add the challenge file `src/assets/challenges/articles.yml` to the level file `src/assets/challenges/level_a1.yml` to the level loader `src/model/level_loader.rs`

[source,rust]
----
include::../src/model/level_loader.rs[lines="14..17,44..56"]
----

== Create new Custom Challenge Design

To create a new custom challenge design, follow these steps:

* Create a new html file in `src/assets/challenges/html` for the challenge design like `src/assets/challenges/custom_articles.html`

[source,html]
----
include::../src/assets/challenges/html/custom_articles.html[]
----

* Create a new css file in `src/assets/challenges/css` for the challenge design like `src/assets/challenges/css/custom_articles.css`

[source,css]
----
include::../src/assets/challenges/css/custom_articles.css[]
----

* Create a new js file in `src/assets/challenges/js` for the challenge design like `src/assets/challenges/js/custom_articles.js`

[source,javascript]
----
include::../src/assets/challenges/js/custom_articles.js[]
----

* Add a new challenge data to the challenges folder like `src/assets/challenges/custom_articles.yml`

[source,yaml]
----
include::../src/assets/challenges/custom_articles.yml[lines=1..20]
----

* Update the level loader `src/model/level_loader.rs` to include the new challenge design

[source,rust]
----
include::../src/model/level_loader.rs[lines="70..84"]
----

* Add the new challenge design to the level file `src/assets/challenges/level_c1.yml`

[source,yaml]
----
include::../src/assets/challenges/level_c1.yml[lines=39..46]
----
