= Developer Guide

This guide provides information for developers who want to contribute to the project.

== Quickstart

Clone the repository

[source,bash]
----
git clone git@github.com:Konnektoren/konnektoren-web-game.git
----

then compile and serve the page with

[source,bash]
----
trunk serve
----

then visit http://localhost:8080

== Repository Structure

The repository is structured as follows:

* `docs/` contains the developer guide
* `src/` contains the source code
* `src/assets/challenges/` contains the challenge assets
* `src/assets/i18n/` contains the internationalization assets
* `styles/` contains the scss styles
* `Cargo.toml` contains the package metadata
* `README.adoc` contains the project documentation

== Contributing

To contribute to the project, follow these steps:

1. Fork the repository
2. Create a new branch
3. Make your changes
4. Push your changes to your fork
5. Open a pull request

== Create a New Challenge Dataset

To create a new challenge dataset, follow these steps:

* Create a new file in `src/assets/challenges/` for the challenge data like `src/assets/challenges/articles.yml`

[source,yaml]
----
include::../src/assets/challenges/articles.yml[lines=1..20]
----

* Add the challenge data to the level file like `src/assets/challenges/levels.yml`

[source,yaml]
----
include::../src/assets/challenges/level_a1.yml[lines=1..11]
----

* Add the challenge file `src/assets/challenges/articles.yml` to the level file `src/assets/challenges/level_a1.yml` to the level loader `src/model/level_loader.rs`

[source,rust]
----
include::../src/model/level_loader.rs[lines="14..17,44..56"]
----
