name: GitHub Pages

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    environment: KONNEKTOREN_BUILD
    env:
      BUILD_DIR_HELP: ./dist_help
      BUILD_DIR_APP: ./dist_app
      BASE_PATH: /
      GOOGLE_REDIRECT_URI_HELP: https://konnektoren.help/backup
      GOOGLE_REDIRECT_URI_APP: https://konnektoren.app/backup
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install just
        uses: extractions/setup-just@v1
        with:
          just-version: "1.14"

      - name: Cache Trunk
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/trunk
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-trunk-${{ hashFiles('**/Trunk.toml') }}

      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Setup Dependencies
        run: |
          just setup-styles

      - name: Setup help domain
        run: |
          BUILD_DIR=${BUILD_DIR_HELP} \
          DOMAIN=https://konnektoren.help \
          GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI_HELP} \
          BASE_PATH=${BASE_PATH} \
          just build
          cp ./CNAME ${BUILD_DIR_HELP}/CNAME

      - name: Setup app domain
        run: |
          BUILD_DIR=${BUILD_DIR_APP} \
          DOMAIN=https://konnektoren.app \
          GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI_APP} \
          BASE_PATH=${BASE_PATH} \
          just build
          echo "konnektoren.app" > ${BUILD_DIR_APP}/CNAME

      - name: Submit to IndexNow
        run: |
          BUILD_DIR=${BUILD_DIR_HELP} just submit-indexnow https://konnektoren.help
          BUILD_DIR=${BUILD_DIR_APP} just submit-indexnow https://konnektoren.app

      - name: Copy common files
        run: |
          for DIR in ${BUILD_DIR_HELP} ${BUILD_DIR_APP}; do
            cp ./robots.txt $DIR/robots.txt
            cp ./policy.html $DIR/policy.html
            cp ./terms.html $DIR/terms.html
            cp ./404.html $DIR/404.html
            cp ./sogousiteverification.txt $DIR/sogousiteverification.txt
            cp ./_redirects $DIR/_redirects
            cp ./_headers $DIR/_headers
          done

      - name: Deploy konnektoren.help
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_DIR_HELP }}
          keep_files: true

      - name: Deploy konnektoren.app
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.APP_DEPLOY_KEY }}
          external_repository: konnektoren/konnektoren.app
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_DIR_APP }}
          keep_files: false
