name: GitHub Pages

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build_and_deploy:
    name: Rust project for all branches
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown

      - name: Set build and public directory for branches
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "BUILD_DIR=./dist" >> $GITHUB_ENV
            echo "PUBLIC_URL=/" >> $GITHUB_ENV
          else
            echo "BUILD_DIR=./dist/wip/${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "PUBLIC_URL=/wip/${GITHUB_REF##*/}/" >> $GITHUB_ENV
          fi

      - run: mkdir -p $BUILD_DIR
      - run: echo $BUILD_DIR $PUBLIC_URL
      - run: trunk build --release --dist $BUILD_DIR --public-url $PUBLIC_URL

      - name: Generate Sitemap
        run: ./scripts/generate_sitemap.sh && cp ./sitemap.xml $BUILD_DIR/sitemap.xml && cp ./sitemap.txt $BUILD_DIR/sitemap.txt && cp ./atom.xml $BUILD_DIR/atom.xml

      - name: Submit to IndexNow
        run: |
          chmod +x ./scripts/indexnow_submit.sh
          ./scripts/indexnow_submit.sh

      - name: Generate Challenge Packages
        run: |
          chmod +x ./scripts/generate_challenge_packages.sh
          ./scripts/generate_challenge_packages.sh

      - name: Copy CNAME
        run: cp ./CNAME $BUILD_DIR/CNAME

      - name: Copy robots.txt
        run: cp ./robots.txt $BUILD_DIR/robots.txt

      - name: Copy policy.html
        run: cp ./policy.html $BUILD_DIR/policy.html

      - name: Copy terms.html
        run: cp ./terms.html $BUILD_DIR/terms.html

      - name: Copy 404.html
        run: cp 404.html $BUILD_DIR/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
