name: GitHub Pages

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown

      - name: Set build directories
        run: |
          echo "BUILD_DIR_HELP=./dist_help" >> $GITHUB_ENV
          echo "BUILD_DIR_APP=./dist_app" >> $GITHUB_ENV
          echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build for konnektoren.help
        run: |
          mkdir -p $BUILD_DIR_HELP
          BASE_PATH=${{ env.BASE_PATH }} trunk build --release --dist $BUILD_DIR_HELP --public-url ${{ env.BASE_PATH }}
          cp ./CNAME $BUILD_DIR_HELP/CNAME

      - name: Build for konnektoren.app
        run: |
          mkdir -p $BUILD_DIR_APP
          BASE_PATH=${{ env.BASE_PATH }} trunk build --release --dist $BUILD_DIR_APP --public-url ${{ env.BASE_PATH }}
          echo "konnektoren.app" > $BUILD_DIR_APP/CNAME

      - name: Generate Sitemaps
        run: |
          chmod +x ./scripts/generate_sitemap.sh
          ./scripts/generate_sitemap.sh
          cp ./sitemap_konnektoren.help.xml $BUILD_DIR_HELP/sitemap.xml
          cp ./sitemap_konnektoren.help.txt $BUILD_DIR_HELP/sitemap.txt
          cp ./atom_konnektoren.help.xml $BUILD_DIR_HELP/atom.xml
          cp ./sitemap_konnektoren.app.xml $BUILD_DIR_APP/sitemap.xml
          cp ./sitemap_konnektoren.app.txt $BUILD_DIR_APP/sitemap.txt
          cp ./atom_konnektoren.app.xml $BUILD_DIR_APP/atom.xml

      - name: Submit to IndexNow for konnektoren.help
        run: |
          chmod +x ./scripts/indexnow_submit.sh
          BUILD_DIR=$BUILD_DIR_HELP DOMAIN=https://konnektoren.help SITEMAP=sitemap.txt ./scripts/indexnow_submit.sh

      - name: Submit to IndexNow for konnektoren.app
        run: |
          chmod +x ./scripts/indexnow_submit.sh
          BUILD_DIR=$BUILD_DIR_APP DOMAIN=https://konnektoren.app SITEMAP=sitemap.txt ./scripts/indexnow_submit.sh
      - name: Generate Challenge Packages for konnektoren.help
        run: |
          chmod +x ./scripts/generate_challenge_packages.sh
          BUILD_DIR=$BUILD_DIR_HELP ./scripts/generate_challenge_packages.sh

      - name: Generate Challenge Packages for konnektoren.app
        run: |
          chmod +x ./scripts/generate_challenge_packages.sh
          BUILD_DIR=$BUILD_DIR_APP ./scripts/generate_challenge_packages.sh

      - name: Copy common files
        run: |
          cp ./robots.txt $BUILD_DIR_HELP/robots.txt
          cp ./policy.html $BUILD_DIR_HELP/policy.html
          cp ./terms.html $BUILD_DIR_HELP/terms.html
          cp ./404.html $BUILD_DIR_HELP/404.html
          cp ./robots.txt $BUILD_DIR_APP/robots.txt
          cp ./policy.html $BUILD_DIR_APP/policy.html
          cp ./terms.html $BUILD_DIR_APP/terms.html
          cp ./404.html $BUILD_DIR_APP/404.html

      - name: Deploy konnektoren.help
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_DIR_HELP }}
          keep_files: true

      - name: Deploy konnektoren.app
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.APP_DEPLOY_KEY }}
          external_repository: konnektoren/konnektoren.app
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_DIR_APP }}
          keep_files: false
